// ISO-3166-1 alpha-2 → { name, flag emoji, [lng, lat] centroid }
export const COUNTRY_INFO: Record<string, { name: string; flag: string; coords: [number, number] }> = {
  US: { name: "United States", flag: "🇺🇸", coords: [-98, 39] },
  CA: { name: "Canada", flag: "🇨🇦", coords: [-106, 56] },
  MX: { name: "Mexico", flag: "🇲🇽", coords: [-102, 23] },
  GT: { name: "Guatemala", flag: "🇬🇹", coords: [-90.2, 15.5] },
  HN: { name: "Honduras", flag: "🇭🇳", coords: [-86.5, 15] },
  SV: { name: "El Salvador", flag: "🇸🇻", coords: [-88.9, 13.8] },
  NI: { name: "Nicaragua", flag: "🇳🇮", coords: [-85, 12.8] },
  CR: { name: "Costa Rica", flag: "🇨🇷", coords: [-84, 10] },
  PA: { name: "Panama", flag: "🇵🇦", coords: [-80, 9] },
  CU: { name: "Cuba", flag: "🇨🇺", coords: [-77.8, 21.5] },
  DO: { name: "Dominican Rep.", flag: "🇩🇴", coords: [-70.7, 19] },
  PR: { name: "Puerto Rico", flag: "🇵🇷", coords: [-66.5, 18.2] },
  CO: { name: "Colombia", flag: "🇨🇴", coords: [-74, 4] },
  VE: { name: "Venezuela", flag: "🇻🇪", coords: [-66, 8] },
  EC: { name: "Ecuador", flag: "🇪🇨", coords: [-78, -1.5] },
  PE: { name: "Peru", flag: "🇵🇪", coords: [-75, -10] },
  BO: { name: "Bolivia", flag: "🇧🇴", coords: [-64, -17] },
  BR: { name: "Brazil", flag: "🇧🇷", coords: [-53, -10] },
  PY: { name: "Paraguay", flag: "🇵🇾", coords: [-58, -23] },
  UY: { name: "Uruguay", flag: "🇺🇾", coords: [-56, -33] },
  AR: { name: "Argentina", flag: "🇦🇷", coords: [-64, -34] },
  CL: { name: "Chile", flag: "🇨🇱", coords: [-71, -35] },
  ES: { name: "Spain", flag: "🇪🇸", coords: [-3.7, 40.4] },
  PT: { name: "Portugal", flag: "🇵🇹", coords: [-8, 39.5] },
  FR: { name: "France", flag: "🇫🇷", coords: [2.5, 46.5] },
  GB: { name: "United Kingdom", flag: "🇬🇧", coords: [-2, 54] },
  IE: { name: "Ireland", flag: "🇮🇪", coords: [-8, 53] },
  DE: { name: "Germany", flag: "🇩🇪", coords: [10.4, 51.2] },
  IT: { name: "Italy", flag: "🇮🇹", coords: [12.5, 42.8] },
  NL: { name: "Netherlands", flag: "🇳🇱", coords: [5.3, 52.1] },
  BE: { name: "Belgium", flag: "🇧🇪", coords: [4.5, 50.5] },
  CH: { name: "Switzerland", flag: "🇨🇭", coords: [8.2, 46.8] },
  AT: { name: "Austria", flag: "🇦🇹", coords: [14.5, 47.5] },
  SE: { name: "Sweden", flag: "🇸🇪", coords: [15, 62] },
  NO: { name: "Norway", flag: "🇳🇴", coords: [10, 62] },
  DK: { name: "Denmark", flag: "🇩🇰", coords: [10, 56] },
  FI: { name: "Finland", flag: "🇫🇮", coords: [26, 64] },
  PL: { name: "Poland", flag: "🇵🇱", coords: [19, 52] },
  CZ: { name: "Czechia", flag: "🇨🇿", coords: [15.5, 49.8] },
  RO: { name: "Romania", flag: "🇷🇴", coords: [25, 46] },
  GR: { name: "Greece", flag: "🇬🇷", coords: [22, 39] },
  TR: { name: "Turkey", flag: "🇹🇷", coords: [35, 39] },
  RU: { name: "Russia", flag: "🇷🇺", coords: [90, 60] },
  UA: { name: "Ukraine", flag: "🇺🇦", coords: [31, 49] },
  IL: { name: "Israel", flag: "🇮🇱", coords: [34.9, 31.5] },
  AE: { name: "UAE", flag: "🇦🇪", coords: [54, 24] },
  SA: { name: "Saudi Arabia", flag: "🇸🇦", coords: [45, 24] },
  EG: { name: "Egypt", flag: "🇪🇬", coords: [30, 26] },
  MA: { name: "Morocco", flag: "🇲🇦", coords: [-6, 32] },
  ZA: { name: "South Africa", flag: "🇿🇦", coords: [25, -29] },
  NG: { name: "Nigeria", flag: "🇳🇬", coords: [8, 9] },
  KE: { name: "Kenya", flag: "🇰🇪", coords: [38, 0] },
  GH: { name: "Ghana", flag: "🇬🇭", coords: [-1, 7.9] },
  TZ: { name: "Tanzania", flag: "🇹🇿", coords: [34.8, -6.3] },
  UG: { name: "Uganda", flag: "🇺🇬", coords: [32.3, 1.3] },
  IN: { name: "India", flag: "🇮🇳", coords: [78, 22] },
  PK: { name: "Pakistan", flag: "🇵🇰", coords: [70, 30] },
  BD: { name: "Bangladesh", flag: "🇧🇩", coords: [90, 24] },
  CN: { name: "China", flag: "🇨🇳", coords: [104, 35] },
  JP: { name: "Japan", flag: "🇯🇵", coords: [138, 36] },
  KR: { name: "South Korea", flag: "🇰🇷", coords: [128, 36] },
  TW: { name: "Taiwan", flag: "🇹🇼", coords: [121, 23.5] },
  HK: { name: "Hong Kong", flag: "🇭🇰", coords: [114, 22.3] },
  SG: { name: "Singapore", flag: "🇸🇬", coords: [104, 1.3] },
  MY: { name: "Malaysia", flag: "🇲🇾", coords: [102, 4] },
  TH: { name: "Thailand", flag: "🇹🇭", coords: [101, 15] },
  VN: { name: "Vietnam", flag: "🇻🇳", coords: [108, 16] },
  ID: { name: "Indonesia", flag: "🇮🇩", coords: [113, -2] },
  PH: { name: "Philippines", flag: "🇵🇭", coords: [122, 13] },
  AU: { name: "Australia", flag: "🇦🇺", coords: [134, -25] },
  NZ: { name: "New Zealand", flag: "🇳🇿", coords: [172, -41] },
};

export function getCountryInfo(code: string | null | undefined) {
  if (!code) return null;
  return COUNTRY_INFO[code.toUpperCase()] || null;
}
