project_id = "opyitzdvvurdyyyzkwwv"

[functions.process-email-queue]
verify_jwt = true

[functions.create-test-checkout]
verify_jwt = false

[functions.create-checkout-prueba]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false
